### ISSUE TITLE
discussion: translate welcome page

### ISSUE THREAD

**Issue by Deardrops** [osu-translate-zh/osu-wiki#15]
需要讨论的并确定要下来的翻译内容：
1. 文章的面向的玩家是谁，他们希望看到一篇什么样的文章？
2. 文章的主题是什么，围绕这个主题有哪些内容可以加入文章中？
3. 文章具体要写哪些东西（列出大纲），需要增删的内容？

**Comment by Deardrops** [comment]
### 个人意见：
1. 文章面向第一次接触osu!的玩家，他们不懂这是个什么游戏，怎么玩，怎么下歌，怎么和别人聊天，等等。他们希望这篇文章可以快速介绍一些入门的知识，并且可以进一步了解这些知识。
2. 文章的主题有两个：面向新人的快速指南，以及wiki中关键内容（值得一读的内容/需要掌握的知识）的简短介绍。总体上来讲，包含的内容有：

> 基础知识：
> - 游戏的总结性介绍
> - 游戏的玩法
> - 关键术语的解释：acc, pp, rank, etc

> 实用技巧：
> - 常用快捷键
>- 找图/下图的姿势（附加内容：镜像网站）

3. 文章大纲：
（待更新）

**Comment by Deardrops** [comment]
## 下面贴出英语 welcome 文章的大纲，供参考：
### 开场介绍语
欢迎加入我们的社区，首先快速介绍一些游戏入门的内容。
### 游戏教程
打开游戏 - play - solo - 选择 osu! tutorial 这首歌 - 开始游戏

介绍游戏中的一些基础物件：

- 圈
- 滑条
- 转盘

### 如何下载一些你喜欢的歌曲
1. 在官网上查找歌曲
2. 下载谱面文件
3. 使用osu加载它
4. 在osu!中玩这张谱面

### 游戏模式
1. 单人游戏
2. 多人游戏

### 竞争
1. 等级
2. pp
3. acc
4. 成就

### 聊天
- 聊天命令
- F8 呼出聊天窗口，聊天频道
- F9 呼出用户列表窗口

### 谱面
如何作图

**Comment by kj415j45** [comment]
ref: ppy/osu-wiki#94

基本要求: 

- [x] 简短而清晰地介绍 osu! 是什么(不得超过 125 字)
- [ ] 链接到新玩家最可能感兴趣的页面
- [ ] 简短介绍谱面及摸图(modding)，然后使用链接指向相关细节
- [ ] 介绍 osu! 的主要活动(世界杯)
- [ ] 简短介绍如何向 wiki 贡献，然后链接到 owcg
- [x] 不要看起来像坨屎

**Comment by kj415j45** [comment]
英文版本：
osu! is a free-to-win rhythm game developed by peppy with four game modes: osu!, a circle clicking sim; osu!taiko, a drum drumming emulator; osu!catch, a fruit salad catcher; osu!mania, a key smashing mania.

**Comment by Deardrops** [comment]
### 个人建议：
> osu!是Windows平台上一个免费的音游游戏，在全世界拥有上百万的玩家和拥有难以计数的歌曲。包含4种游戏模式，提供单机和联机的游戏方式，支持包括中文在内的多国语言。osu!拥有谱面分数和个人实力排行榜，玩家可以查看自定义游戏界面，在游戏内观看游戏直播和录像，制作和上传自己的谱面。

### 解释：
第一段话简单地介绍一下这是个什么游戏，有些什么特别的地方。让小白有个基本了解。
建议把介绍游戏模式和其他补充内容放到接下来的段落。比如我们接着可以说：
> osu! 有四种游戏模式，分别是：.......
> osu! 最初由peppy个人维护，目前新客户端已完全开源，由osu!dev团队负责开发和维护。

**Comment by lslqtz** [comment]
~~这里不是ppy的分支吧
屙屎是由peppy开发的音乐播放器，内置四个小游戏，具备完善的暂停播放功能，现在还开源了方便找出播放器的bug，这个播放器还支持播放视频和自制压缩视频格式(storyboard)，但是暂时不支持硬解~~
已经有的部分可以用链接链向对应的 wiki 页，大幅减轻工作量
关于上一句：osu! 后面说是要跨平台，所以写 Windows 会不会不太好

**Comment by Deardrops** [comment]
@lslqtz osu!是一个免费的多平台音乐游戏，.....

**Comment by kj415j45** [comment]
---
osu! 是一款有着四个模式的免费音乐游戏。它在全世界有上千万的玩家，并拥有上万张谱面。你可以离线或者在线游玩，并与世界各地玩家同台竞技。同时，所有人都可以为他喜欢的歌制作并上传自己的谱面，然后与全球玩家一同分享！
---
osu! is a free-to-win rhythm game with four game modes. It has millions of players and thousands of songs, you can play those songs offline or online and compete with others. Everyone can make beatmaps for their favourite songs and share them with players around the world!
---
